export const PRODUCTS_LIST_REQUEST='PRODUCTS_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCTS_DRTAILS_REQUEST='PRODUCTS_DRTAILS_REQUEST';
export const PRODUCT_DRTAILS_SUCCESS='PRODUCT_DRTAILS_SUCCESS';
export const PRODUCT_DRTAILS_FAIL='PRODUCT_DRTAILS_FAIL';